# Generated by Django 5.0.2 on 2024-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLProgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('passwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
